// Generated by gencpp from file gazebo_msgs_new/ApplyJointEffort.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_APPLYJOINTEFFORT_H
#define GAZEBO_MSGS_NEW_MESSAGE_APPLYJOINTEFFORT_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/ApplyJointEffortRequest.h>
#include <gazebo_msgs_new/ApplyJointEffortResponse.h>


namespace gazebo_msgs_new
{

struct ApplyJointEffort
{

typedef ApplyJointEffortRequest Request;
typedef ApplyJointEffortResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ApplyJointEffort
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::ApplyJointEffort > {
  static const char* value()
  {
    return "c0039811b8cc919490b3cff748cdf46b";
  }

  static const char* value(const ::gazebo_msgs_new::ApplyJointEffort&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::ApplyJointEffort > {
  static const char* value()
  {
    return "gazebo_msgs_new/ApplyJointEffort";
  }

  static const char* value(const ::gazebo_msgs_new::ApplyJointEffort&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::ApplyJointEffortRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::ApplyJointEffort >
template<>
struct MD5Sum< ::gazebo_msgs_new::ApplyJointEffortRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs_new::ApplyJointEffortRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::ApplyJointEffortRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::ApplyJointEffort >
template<>
struct DataType< ::gazebo_msgs_new::ApplyJointEffortRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs_new::ApplyJointEffortRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::ApplyJointEffortResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::ApplyJointEffort >
template<>
struct MD5Sum< ::gazebo_msgs_new::ApplyJointEffortResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs_new::ApplyJointEffortResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::ApplyJointEffortResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::ApplyJointEffort >
template<>
struct DataType< ::gazebo_msgs_new::ApplyJointEffortResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs_new::ApplyJointEffortResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_APPLYJOINTEFFORT_H
