// Generated by gencpp from file gazebo_msgs_new/BodyRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_BODYREQUEST_H
#define GAZEBO_MSGS_NEW_MESSAGE_BODYREQUEST_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/BodyRequestRequest.h>
#include <gazebo_msgs_new/BodyRequestResponse.h>


namespace gazebo_msgs_new
{

struct BodyRequest
{

typedef BodyRequestRequest Request;
typedef BodyRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BodyRequest
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::BodyRequest > {
  static const char* value()
  {
    return "5eade9afe7f232d78005bd0cafeab755";
  }

  static const char* value(const ::gazebo_msgs_new::BodyRequest&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::BodyRequest > {
  static const char* value()
  {
    return "gazebo_msgs_new/BodyRequest";
  }

  static const char* value(const ::gazebo_msgs_new::BodyRequest&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::BodyRequestRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::BodyRequest >
template<>
struct MD5Sum< ::gazebo_msgs_new::BodyRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs_new::BodyRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::BodyRequestRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::BodyRequest >
template<>
struct DataType< ::gazebo_msgs_new::BodyRequestRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs_new::BodyRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::BodyRequestResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::BodyRequest >
template<>
struct MD5Sum< ::gazebo_msgs_new::BodyRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs_new::BodyRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::BodyRequestResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::BodyRequest >
template<>
struct DataType< ::gazebo_msgs_new::BodyRequestResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs_new::BodyRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_BODYREQUEST_H
