// Generated by gencpp from file gazebo_msgs_new/DeleteLight.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_DELETELIGHT_H
#define GAZEBO_MSGS_NEW_MESSAGE_DELETELIGHT_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/DeleteLightRequest.h>
#include <gazebo_msgs_new/DeleteLightResponse.h>


namespace gazebo_msgs_new
{

struct DeleteLight
{

typedef DeleteLightRequest Request;
typedef DeleteLightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteLight
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::DeleteLight > {
  static const char* value()
  {
    return "ae11ea8100d536d5b92c2b5917abf912";
  }

  static const char* value(const ::gazebo_msgs_new::DeleteLight&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::DeleteLight > {
  static const char* value()
  {
    return "gazebo_msgs_new/DeleteLight";
  }

  static const char* value(const ::gazebo_msgs_new::DeleteLight&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteLightRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteLight >
template<>
struct MD5Sum< ::gazebo_msgs_new::DeleteLightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::DeleteLight >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteLightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::DeleteLightRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::DeleteLight >
template<>
struct DataType< ::gazebo_msgs_new::DeleteLightRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::DeleteLight >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteLightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteLightResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteLight >
template<>
struct MD5Sum< ::gazebo_msgs_new::DeleteLightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::DeleteLight >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteLightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::DeleteLightResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::DeleteLight >
template<>
struct DataType< ::gazebo_msgs_new::DeleteLightResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::DeleteLight >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteLightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_DELETELIGHT_H
