// Generated by gencpp from file gazebo_msgs_new/DeleteModel.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_DELETEMODEL_H
#define GAZEBO_MSGS_NEW_MESSAGE_DELETEMODEL_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/DeleteModelRequest.h>
#include <gazebo_msgs_new/DeleteModelResponse.h>


namespace gazebo_msgs_new
{

struct DeleteModel
{

typedef DeleteModelRequest Request;
typedef DeleteModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteModel
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::DeleteModel > {
  static const char* value()
  {
    return "9ce56b4e9e54616de25d796dc972a262";
  }

  static const char* value(const ::gazebo_msgs_new::DeleteModel&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::DeleteModel > {
  static const char* value()
  {
    return "gazebo_msgs_new/DeleteModel";
  }

  static const char* value(const ::gazebo_msgs_new::DeleteModel&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteModelRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteModel >
template<>
struct MD5Sum< ::gazebo_msgs_new::DeleteModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::DeleteModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::DeleteModelRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::DeleteModel >
template<>
struct DataType< ::gazebo_msgs_new::DeleteModelRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::DeleteModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteModelResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::DeleteModel >
template<>
struct MD5Sum< ::gazebo_msgs_new::DeleteModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::DeleteModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::DeleteModelResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::DeleteModel >
template<>
struct DataType< ::gazebo_msgs_new::DeleteModelResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::DeleteModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::DeleteModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_DELETEMODEL_H
