// Generated by gencpp from file gazebo_msgs_new/GetLinkProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_GETLINKPROPERTIES_H
#define GAZEBO_MSGS_NEW_MESSAGE_GETLINKPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/GetLinkPropertiesRequest.h>
#include <gazebo_msgs_new/GetLinkPropertiesResponse.h>


namespace gazebo_msgs_new
{

struct GetLinkProperties
{

typedef GetLinkPropertiesRequest Request;
typedef GetLinkPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLinkProperties
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::GetLinkProperties > {
  static const char* value()
  {
    return "0e06a70386d0ee3fb880c02f23fcd821";
  }

  static const char* value(const ::gazebo_msgs_new::GetLinkProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::GetLinkProperties > {
  static const char* value()
  {
    return "gazebo_msgs_new/GetLinkProperties";
  }

  static const char* value(const ::gazebo_msgs_new::GetLinkProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkPropertiesRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetLinkPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetLinkProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetLinkPropertiesRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::GetLinkProperties >
template<>
struct DataType< ::gazebo_msgs_new::GetLinkPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetLinkProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkPropertiesResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetLinkPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetLinkProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetLinkPropertiesResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::GetLinkProperties >
template<>
struct DataType< ::gazebo_msgs_new::GetLinkPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetLinkProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_GETLINKPROPERTIES_H
