// Generated by gencpp from file gazebo_msgs_new/GetLinkState.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_GETLINKSTATE_H
#define GAZEBO_MSGS_NEW_MESSAGE_GETLINKSTATE_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/GetLinkStateRequest.h>
#include <gazebo_msgs_new/GetLinkStateResponse.h>


namespace gazebo_msgs_new
{

struct GetLinkState
{

typedef GetLinkStateRequest Request;
typedef GetLinkStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLinkState
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::GetLinkState > {
  static const char* value()
  {
    return "09d6c98cce97b35f7ab9bd70300657ab";
  }

  static const char* value(const ::gazebo_msgs_new::GetLinkState&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::GetLinkState > {
  static const char* value()
  {
    return "gazebo_msgs_new/GetLinkState";
  }

  static const char* value(const ::gazebo_msgs_new::GetLinkState&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkStateRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkState >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetLinkStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetLinkStateRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::GetLinkState >
template<>
struct DataType< ::gazebo_msgs_new::GetLinkStateRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkStateResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetLinkState >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetLinkStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetLinkStateResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::GetLinkState >
template<>
struct DataType< ::gazebo_msgs_new::GetLinkStateResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetLinkStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_GETLINKSTATE_H
