// Generated by gencpp from file gazebo_msgs_new/GetModelProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_GETMODELPROPERTIES_H
#define GAZEBO_MSGS_NEW_MESSAGE_GETMODELPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/GetModelPropertiesRequest.h>
#include <gazebo_msgs_new/GetModelPropertiesResponse.h>


namespace gazebo_msgs_new
{

struct GetModelProperties
{

typedef GetModelPropertiesRequest Request;
typedef GetModelPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetModelProperties
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::GetModelProperties > {
  static const char* value()
  {
    return "5717f7bd34ed990fa80e28b3015027a3";
  }

  static const char* value(const ::gazebo_msgs_new::GetModelProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::GetModelProperties > {
  static const char* value()
  {
    return "gazebo_msgs_new/GetModelProperties";
  }

  static const char* value(const ::gazebo_msgs_new::GetModelProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelPropertiesRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetModelPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetModelProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetModelPropertiesRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::GetModelProperties >
template<>
struct DataType< ::gazebo_msgs_new::GetModelPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetModelProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelPropertiesResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetModelPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetModelProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetModelPropertiesResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::GetModelProperties >
template<>
struct DataType< ::gazebo_msgs_new::GetModelPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetModelProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_GETMODELPROPERTIES_H
