// Generated by gencpp from file gazebo_msgs_new/GetModelState.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_GETMODELSTATE_H
#define GAZEBO_MSGS_NEW_MESSAGE_GETMODELSTATE_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/GetModelStateRequest.h>
#include <gazebo_msgs_new/GetModelStateResponse.h>


namespace gazebo_msgs_new
{

struct GetModelState
{

typedef GetModelStateRequest Request;
typedef GetModelStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetModelState
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::GetModelState > {
  static const char* value()
  {
    return "4c515e936d3319c9610c559c60bfc3d4";
  }

  static const char* value(const ::gazebo_msgs_new::GetModelState&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::GetModelState > {
  static const char* value()
  {
    return "gazebo_msgs_new/GetModelState";
  }

  static const char* value(const ::gazebo_msgs_new::GetModelState&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelStateRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelState >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetModelStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetModelStateRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::GetModelState >
template<>
struct DataType< ::gazebo_msgs_new::GetModelStateRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelStateResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetModelState >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetModelStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetModelStateResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::GetModelState >
template<>
struct DataType< ::gazebo_msgs_new::GetModelStateResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetModelStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_GETMODELSTATE_H
