// Generated by gencpp from file gazebo_msgs_new/GetPhysicsProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_GETPHYSICSPROPERTIES_H
#define GAZEBO_MSGS_NEW_MESSAGE_GETPHYSICSPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/GetPhysicsPropertiesRequest.h>
#include <gazebo_msgs_new/GetPhysicsPropertiesResponse.h>


namespace gazebo_msgs_new
{

struct GetPhysicsProperties
{

typedef GetPhysicsPropertiesRequest Request;
typedef GetPhysicsPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPhysicsProperties
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::GetPhysicsProperties > {
  static const char* value()
  {
    return "575a5e74786981b7df2e3afc567693a6";
  }

  static const char* value(const ::gazebo_msgs_new::GetPhysicsProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::GetPhysicsProperties > {
  static const char* value()
  {
    return "gazebo_msgs_new/GetPhysicsProperties";
  }

  static const char* value(const ::gazebo_msgs_new::GetPhysicsProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::GetPhysicsPropertiesRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetPhysicsProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetPhysicsPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetPhysicsPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetPhysicsPropertiesRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::GetPhysicsProperties >
template<>
struct DataType< ::gazebo_msgs_new::GetPhysicsPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetPhysicsPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::GetPhysicsPropertiesResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::GetPhysicsProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::GetPhysicsPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::GetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetPhysicsPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::GetPhysicsPropertiesResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::GetPhysicsProperties >
template<>
struct DataType< ::gazebo_msgs_new::GetPhysicsPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::GetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::GetPhysicsPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_GETPHYSICSPROPERTIES_H
