// Generated by gencpp from file gazebo_msgs_new/SetJointProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_SETJOINTPROPERTIES_H
#define GAZEBO_MSGS_NEW_MESSAGE_SETJOINTPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/SetJointPropertiesRequest.h>
#include <gazebo_msgs_new/SetJointPropertiesResponse.h>


namespace gazebo_msgs_new
{

struct SetJointProperties
{

typedef SetJointPropertiesRequest Request;
typedef SetJointPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointProperties
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::SetJointProperties > {
  static const char* value()
  {
    return "15a76e921b1410c698d82782ea5fa370";
  }

  static const char* value(const ::gazebo_msgs_new::SetJointProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::SetJointProperties > {
  static const char* value()
  {
    return "gazebo_msgs_new/SetJointProperties";
  }

  static const char* value(const ::gazebo_msgs_new::SetJointProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointPropertiesRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::SetJointPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SetJointPropertiesRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::SetJointProperties >
template<>
struct DataType< ::gazebo_msgs_new::SetJointPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointPropertiesResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointProperties >
template<>
struct MD5Sum< ::gazebo_msgs_new::SetJointPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SetJointPropertiesResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::SetJointProperties >
template<>
struct DataType< ::gazebo_msgs_new::SetJointPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_SETJOINTPROPERTIES_H
