// Generated by gencpp from file gazebo_msgs_new/SetJointTrajectory.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_SETJOINTTRAJECTORY_H
#define GAZEBO_MSGS_NEW_MESSAGE_SETJOINTTRAJECTORY_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/SetJointTrajectoryRequest.h>
#include <gazebo_msgs_new/SetJointTrajectoryResponse.h>


namespace gazebo_msgs_new
{

struct SetJointTrajectory
{

typedef SetJointTrajectoryRequest Request;
typedef SetJointTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointTrajectory
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::SetJointTrajectory > {
  static const char* value()
  {
    return "88f5c10979e3f9649d5ae87a3b12aa65";
  }

  static const char* value(const ::gazebo_msgs_new::SetJointTrajectory&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::SetJointTrajectory > {
  static const char* value()
  {
    return "gazebo_msgs_new/SetJointTrajectory";
  }

  static const char* value(const ::gazebo_msgs_new::SetJointTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointTrajectoryRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointTrajectory >
template<>
struct MD5Sum< ::gazebo_msgs_new::SetJointTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SetJointTrajectory >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SetJointTrajectoryRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::SetJointTrajectory >
template<>
struct DataType< ::gazebo_msgs_new::SetJointTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SetJointTrajectory >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointTrajectoryResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SetJointTrajectory >
template<>
struct MD5Sum< ::gazebo_msgs_new::SetJointTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SetJointTrajectory >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SetJointTrajectoryResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::SetJointTrajectory >
template<>
struct DataType< ::gazebo_msgs_new::SetJointTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SetJointTrajectory >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetJointTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_SETJOINTTRAJECTORY_H
