// Generated by gencpp from file gazebo_msgs_new/SetLinkState.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_SETLINKSTATE_H
#define GAZEBO_MSGS_NEW_MESSAGE_SETLINKSTATE_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/SetLinkStateRequest.h>
#include <gazebo_msgs_new/SetLinkStateResponse.h>


namespace gazebo_msgs_new
{

struct SetLinkState
{

typedef SetLinkStateRequest Request;
typedef SetLinkStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLinkState
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::SetLinkState > {
  static const char* value()
  {
    return "8a5146eb66ae4d26b0860b08f3f271be";
  }

  static const char* value(const ::gazebo_msgs_new::SetLinkState&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::SetLinkState > {
  static const char* value()
  {
    return "gazebo_msgs_new/SetLinkState";
  }

  static const char* value(const ::gazebo_msgs_new::SetLinkState&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::SetLinkStateRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SetLinkState >
template<>
struct MD5Sum< ::gazebo_msgs_new::SetLinkStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetLinkStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SetLinkStateRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::SetLinkState >
template<>
struct DataType< ::gazebo_msgs_new::SetLinkStateRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetLinkStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::SetLinkStateResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SetLinkState >
template<>
struct MD5Sum< ::gazebo_msgs_new::SetLinkStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetLinkStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SetLinkStateResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::SetLinkState >
template<>
struct DataType< ::gazebo_msgs_new::SetLinkStateResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SetLinkStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_SETLINKSTATE_H
