// Generated by gencpp from file gazebo_msgs_new/SpawnModel.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_NEW_MESSAGE_SPAWNMODEL_H
#define GAZEBO_MSGS_NEW_MESSAGE_SPAWNMODEL_H

#include <ros/service_traits.h>


#include <gazebo_msgs_new/SpawnModelRequest.h>
#include <gazebo_msgs_new/SpawnModelResponse.h>


namespace gazebo_msgs_new
{

struct SpawnModel
{

typedef SpawnModelRequest Request;
typedef SpawnModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnModel
} // namespace gazebo_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs_new::SpawnModel > {
  static const char* value()
  {
    return "9ed9c82c96abe1a00c3e8cdaeee24413";
  }

  static const char* value(const ::gazebo_msgs_new::SpawnModel&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs_new::SpawnModel > {
  static const char* value()
  {
    return "gazebo_msgs_new/SpawnModel";
  }

  static const char* value(const ::gazebo_msgs_new::SpawnModel&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs_new::SpawnModelRequest> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SpawnModel >
template<>
struct MD5Sum< ::gazebo_msgs_new::SpawnModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SpawnModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SpawnModelRequest> should match
// service_traits::DataType< ::gazebo_msgs_new::SpawnModel >
template<>
struct DataType< ::gazebo_msgs_new::SpawnModelRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SpawnModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs_new::SpawnModelResponse> should match
// service_traits::MD5Sum< ::gazebo_msgs_new::SpawnModel >
template<>
struct MD5Sum< ::gazebo_msgs_new::SpawnModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs_new::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SpawnModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs_new::SpawnModelResponse> should match
// service_traits::DataType< ::gazebo_msgs_new::SpawnModel >
template<>
struct DataType< ::gazebo_msgs_new::SpawnModelResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs_new::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs_new::SpawnModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_NEW_MESSAGE_SPAWNMODEL_H
