// Generated by gencpp from file robotnik_msgs_new/ack_alarm.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_ACK_ALARM_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_ACK_ALARM_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/ack_alarmRequest.h>
#include <robotnik_msgs_new/ack_alarmResponse.h>


namespace robotnik_msgs_new
{

struct ack_alarm
{

typedef ack_alarmRequest Request;
typedef ack_alarmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ack_alarm
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::ack_alarm > {
  static const char* value()
  {
    return "5691e91cfff5344662d430d7da60497e";
  }

  static const char* value(const ::robotnik_msgs_new::ack_alarm&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::ack_alarm > {
  static const char* value()
  {
    return "robotnik_msgs_new/ack_alarm";
  }

  static const char* value(const ::robotnik_msgs_new::ack_alarm&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::ack_alarmRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::ack_alarm >
template<>
struct MD5Sum< ::robotnik_msgs_new::ack_alarmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::ack_alarm >::value();
  }
  static const char* value(const ::robotnik_msgs_new::ack_alarmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::ack_alarmRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::ack_alarm >
template<>
struct DataType< ::robotnik_msgs_new::ack_alarmRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::ack_alarm >::value();
  }
  static const char* value(const ::robotnik_msgs_new::ack_alarmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::ack_alarmResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::ack_alarm >
template<>
struct MD5Sum< ::robotnik_msgs_new::ack_alarmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::ack_alarm >::value();
  }
  static const char* value(const ::robotnik_msgs_new::ack_alarmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::ack_alarmResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::ack_alarm >
template<>
struct DataType< ::robotnik_msgs_new::ack_alarmResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::ack_alarm >::value();
  }
  static const char* value(const ::robotnik_msgs_new::ack_alarmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_ACK_ALARM_H
