// Generated by gencpp from file robotnik_msgs_new/get_alarms.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_GET_ALARMS_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_GET_ALARMS_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/get_alarmsRequest.h>
#include <robotnik_msgs_new/get_alarmsResponse.h>


namespace robotnik_msgs_new
{

struct get_alarms
{

typedef get_alarmsRequest Request;
typedef get_alarmsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_alarms
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::get_alarms > {
  static const char* value()
  {
    return "4550354b6bec7529a93833858063eaed";
  }

  static const char* value(const ::robotnik_msgs_new::get_alarms&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::get_alarms > {
  static const char* value()
  {
    return "robotnik_msgs_new/get_alarms";
  }

  static const char* value(const ::robotnik_msgs_new::get_alarms&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::get_alarmsRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::get_alarms >
template<>
struct MD5Sum< ::robotnik_msgs_new::get_alarmsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::get_alarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::get_alarmsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::get_alarmsRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::get_alarms >
template<>
struct DataType< ::robotnik_msgs_new::get_alarmsRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::get_alarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::get_alarmsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::get_alarmsResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::get_alarms >
template<>
struct MD5Sum< ::robotnik_msgs_new::get_alarmsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::get_alarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::get_alarmsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::get_alarmsResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::get_alarms >
template<>
struct DataType< ::robotnik_msgs_new::get_alarmsResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::get_alarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::get_alarmsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_GET_ALARMS_H
