// Generated by gencpp from file robotnik_msgs_new/GetBool.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_GETBOOL_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_GETBOOL_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/GetBoolRequest.h>
#include <robotnik_msgs_new/GetBoolResponse.h>


namespace robotnik_msgs_new
{

struct GetBool
{

typedef GetBoolRequest Request;
typedef GetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBool
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::GetBool > {
  static const char* value()
  {
    return "43f76a855b16e988566e147b692f2fab";
  }

  static const char* value(const ::robotnik_msgs_new::GetBool&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::GetBool > {
  static const char* value()
  {
    return "robotnik_msgs_new/GetBool";
  }

  static const char* value(const ::robotnik_msgs_new::GetBool&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::GetBoolRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::GetBool >
template<>
struct MD5Sum< ::robotnik_msgs_new::GetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::GetBool >::value();
  }
  static const char* value(const ::robotnik_msgs_new::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::GetBoolRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::GetBool >
template<>
struct DataType< ::robotnik_msgs_new::GetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::GetBool >::value();
  }
  static const char* value(const ::robotnik_msgs_new::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::GetBoolResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::GetBool >
template<>
struct MD5Sum< ::robotnik_msgs_new::GetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::GetBool >::value();
  }
  static const char* value(const ::robotnik_msgs_new::GetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::GetBoolResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::GetBool >
template<>
struct DataType< ::robotnik_msgs_new::GetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::GetBool >::value();
  }
  static const char* value(const ::robotnik_msgs_new::GetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_GETBOOL_H
