// Generated by gencpp from file robotnik_msgs_new/home.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_HOME_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_HOME_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/homeRequest.h>
#include <robotnik_msgs_new/homeResponse.h>


namespace robotnik_msgs_new
{

struct home
{

typedef homeRequest Request;
typedef homeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct home
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::home > {
  static const char* value()
  {
    return "be1cffdc9b615c7812c8c2b842784922";
  }

  static const char* value(const ::robotnik_msgs_new::home&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::home > {
  static const char* value()
  {
    return "robotnik_msgs_new/home";
  }

  static const char* value(const ::robotnik_msgs_new::home&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::homeRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::home >
template<>
struct MD5Sum< ::robotnik_msgs_new::homeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::home >::value();
  }
  static const char* value(const ::robotnik_msgs_new::homeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::homeRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::home >
template<>
struct DataType< ::robotnik_msgs_new::homeRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::home >::value();
  }
  static const char* value(const ::robotnik_msgs_new::homeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::homeResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::home >
template<>
struct MD5Sum< ::robotnik_msgs_new::homeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::home >::value();
  }
  static const char* value(const ::robotnik_msgs_new::homeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::homeResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::home >
template<>
struct DataType< ::robotnik_msgs_new::homeResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::home >::value();
  }
  static const char* value(const ::robotnik_msgs_new::homeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_HOME_H
