// Generated by gencpp from file robotnik_msgs_new/InsertTask.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_INSERTTASK_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_INSERTTASK_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/InsertTaskRequest.h>
#include <robotnik_msgs_new/InsertTaskResponse.h>


namespace robotnik_msgs_new
{

struct InsertTask
{

typedef InsertTaskRequest Request;
typedef InsertTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InsertTask
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::InsertTask > {
  static const char* value()
  {
    return "36ad6270fb0855e3101179d36268dd90";
  }

  static const char* value(const ::robotnik_msgs_new::InsertTask&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::InsertTask > {
  static const char* value()
  {
    return "robotnik_msgs_new/InsertTask";
  }

  static const char* value(const ::robotnik_msgs_new::InsertTask&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::InsertTaskRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::InsertTask >
template<>
struct MD5Sum< ::robotnik_msgs_new::InsertTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::InsertTask >::value();
  }
  static const char* value(const ::robotnik_msgs_new::InsertTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::InsertTaskRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::InsertTask >
template<>
struct DataType< ::robotnik_msgs_new::InsertTaskRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::InsertTask >::value();
  }
  static const char* value(const ::robotnik_msgs_new::InsertTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::InsertTaskResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::InsertTask >
template<>
struct MD5Sum< ::robotnik_msgs_new::InsertTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::InsertTask >::value();
  }
  static const char* value(const ::robotnik_msgs_new::InsertTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::InsertTaskResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::InsertTask >
template<>
struct DataType< ::robotnik_msgs_new::InsertTaskResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::InsertTask >::value();
  }
  static const char* value(const ::robotnik_msgs_new::InsertTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_INSERTTASK_H
