// Generated by gencpp from file robotnik_msgs_new/QueryAlarms.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_QUERYALARMS_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_QUERYALARMS_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/QueryAlarmsRequest.h>
#include <robotnik_msgs_new/QueryAlarmsResponse.h>


namespace robotnik_msgs_new
{

struct QueryAlarms
{

typedef QueryAlarmsRequest Request;
typedef QueryAlarmsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryAlarms
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::QueryAlarms > {
  static const char* value()
  {
    return "a3f95993dac9d6abc16a8e0ab77695c5";
  }

  static const char* value(const ::robotnik_msgs_new::QueryAlarms&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::QueryAlarms > {
  static const char* value()
  {
    return "robotnik_msgs_new/QueryAlarms";
  }

  static const char* value(const ::robotnik_msgs_new::QueryAlarms&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::QueryAlarmsRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::QueryAlarms >
template<>
struct MD5Sum< ::robotnik_msgs_new::QueryAlarmsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::QueryAlarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::QueryAlarmsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::QueryAlarmsRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::QueryAlarms >
template<>
struct DataType< ::robotnik_msgs_new::QueryAlarmsRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::QueryAlarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::QueryAlarmsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::QueryAlarmsResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::QueryAlarms >
template<>
struct MD5Sum< ::robotnik_msgs_new::QueryAlarmsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::QueryAlarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::QueryAlarmsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::QueryAlarmsResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::QueryAlarms >
template<>
struct DataType< ::robotnik_msgs_new::QueryAlarmsResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::QueryAlarms >::value();
  }
  static const char* value(const ::robotnik_msgs_new::QueryAlarmsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_QUERYALARMS_H
