// Generated by gencpp from file robotnik_msgs_new/set_height.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_SET_HEIGHT_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_SET_HEIGHT_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/set_heightRequest.h>
#include <robotnik_msgs_new/set_heightResponse.h>


namespace robotnik_msgs_new
{

struct set_height
{

typedef set_heightRequest Request;
typedef set_heightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_height
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::set_height > {
  static const char* value()
  {
    return "30c54779fb893ca6d32239f321774b5f";
  }

  static const char* value(const ::robotnik_msgs_new::set_height&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::set_height > {
  static const char* value()
  {
    return "robotnik_msgs_new/set_height";
  }

  static const char* value(const ::robotnik_msgs_new::set_height&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::set_heightRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::set_height >
template<>
struct MD5Sum< ::robotnik_msgs_new::set_heightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::set_height >::value();
  }
  static const char* value(const ::robotnik_msgs_new::set_heightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::set_heightRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::set_height >
template<>
struct DataType< ::robotnik_msgs_new::set_heightRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::set_height >::value();
  }
  static const char* value(const ::robotnik_msgs_new::set_heightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::set_heightResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::set_height >
template<>
struct MD5Sum< ::robotnik_msgs_new::set_heightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::set_height >::value();
  }
  static const char* value(const ::robotnik_msgs_new::set_heightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::set_heightResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::set_height >
template<>
struct DataType< ::robotnik_msgs_new::set_heightResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::set_height >::value();
  }
  static const char* value(const ::robotnik_msgs_new::set_heightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_SET_HEIGHT_H
