// Generated by gencpp from file robotnik_msgs_new/SetBuzzer.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_SETBUZZER_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_SETBUZZER_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/SetBuzzerRequest.h>
#include <robotnik_msgs_new/SetBuzzerResponse.h>


namespace robotnik_msgs_new
{

struct SetBuzzer
{

typedef SetBuzzerRequest Request;
typedef SetBuzzerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBuzzer
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::SetBuzzer > {
  static const char* value()
  {
    return "41793a7387718993b9d0e132905ea3e3";
  }

  static const char* value(const ::robotnik_msgs_new::SetBuzzer&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::SetBuzzer > {
  static const char* value()
  {
    return "robotnik_msgs_new/SetBuzzer";
  }

  static const char* value(const ::robotnik_msgs_new::SetBuzzer&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::SetBuzzerRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetBuzzer >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetBuzzerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetBuzzer >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetBuzzerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetBuzzerRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::SetBuzzer >
template<>
struct DataType< ::robotnik_msgs_new::SetBuzzerRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetBuzzer >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetBuzzerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::SetBuzzerResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetBuzzer >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetBuzzerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetBuzzer >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetBuzzerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetBuzzerResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::SetBuzzer >
template<>
struct DataType< ::robotnik_msgs_new::SetBuzzerResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetBuzzer >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetBuzzerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_SETBUZZER_H
