// Generated by gencpp from file robotnik_msgs_new/SetElevator.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_SETELEVATOR_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_SETELEVATOR_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/SetElevatorRequest.h>
#include <robotnik_msgs_new/SetElevatorResponse.h>


namespace robotnik_msgs_new
{

struct SetElevator
{

typedef SetElevatorRequest Request;
typedef SetElevatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetElevator
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::SetElevator > {
  static const char* value()
  {
    return "b0ce8ab263ff08692a79c34185b69763";
  }

  static const char* value(const ::robotnik_msgs_new::SetElevator&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::SetElevator > {
  static const char* value()
  {
    return "robotnik_msgs_new/SetElevator";
  }

  static const char* value(const ::robotnik_msgs_new::SetElevator&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::SetElevatorRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetElevator >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetElevatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetElevator >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetElevatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetElevatorRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::SetElevator >
template<>
struct DataType< ::robotnik_msgs_new::SetElevatorRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetElevator >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetElevatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::SetElevatorResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetElevator >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetElevatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetElevator >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetElevatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetElevatorResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::SetElevator >
template<>
struct DataType< ::robotnik_msgs_new::SetElevatorResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetElevator >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetElevatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_SETELEVATOR_H
