// Generated by gencpp from file robotnik_msgs_new/SetMotorPID.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_SETMOTORPID_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_SETMOTORPID_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/SetMotorPIDRequest.h>
#include <robotnik_msgs_new/SetMotorPIDResponse.h>


namespace robotnik_msgs_new
{

struct SetMotorPID
{

typedef SetMotorPIDRequest Request;
typedef SetMotorPIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotorPID
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::SetMotorPID > {
  static const char* value()
  {
    return "b471f23ed4110be72a67eb0fa77abae1";
  }

  static const char* value(const ::robotnik_msgs_new::SetMotorPID&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::SetMotorPID > {
  static const char* value()
  {
    return "robotnik_msgs_new/SetMotorPID";
  }

  static const char* value(const ::robotnik_msgs_new::SetMotorPID&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::SetMotorPIDRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetMotorPID >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetMotorPIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetMotorPID >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetMotorPIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetMotorPIDRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::SetMotorPID >
template<>
struct DataType< ::robotnik_msgs_new::SetMotorPIDRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetMotorPID >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetMotorPIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::SetMotorPIDResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetMotorPID >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetMotorPIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetMotorPID >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetMotorPIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetMotorPIDResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::SetMotorPID >
template<>
struct DataType< ::robotnik_msgs_new::SetMotorPIDResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetMotorPID >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetMotorPIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_SETMOTORPID_H
