// Generated by gencpp from file robotnik_msgs_new/SetNamedDigitalOutput.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_NEW_MESSAGE_SETNAMEDDIGITALOUTPUT_H
#define ROBOTNIK_MSGS_NEW_MESSAGE_SETNAMEDDIGITALOUTPUT_H

#include <ros/service_traits.h>


#include <robotnik_msgs_new/SetNamedDigitalOutputRequest.h>
#include <robotnik_msgs_new/SetNamedDigitalOutputResponse.h>


namespace robotnik_msgs_new
{

struct SetNamedDigitalOutput
{

typedef SetNamedDigitalOutputRequest Request;
typedef SetNamedDigitalOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetNamedDigitalOutput
} // namespace robotnik_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutput > {
  static const char* value()
  {
    return "2025a1879a2ece340190f3058951822d";
  }

  static const char* value(const ::robotnik_msgs_new::SetNamedDigitalOutput&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs_new::SetNamedDigitalOutput > {
  static const char* value()
  {
    return "robotnik_msgs_new/SetNamedDigitalOutput";
  }

  static const char* value(const ::robotnik_msgs_new::SetNamedDigitalOutput&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutputRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutput >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutput >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetNamedDigitalOutputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetNamedDigitalOutputRequest> should match
// service_traits::DataType< ::robotnik_msgs_new::SetNamedDigitalOutput >
template<>
struct DataType< ::robotnik_msgs_new::SetNamedDigitalOutputRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetNamedDigitalOutput >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetNamedDigitalOutputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutputResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutput >
template<>
struct MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs_new::SetNamedDigitalOutput >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetNamedDigitalOutputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs_new::SetNamedDigitalOutputResponse> should match
// service_traits::DataType< ::robotnik_msgs_new::SetNamedDigitalOutput >
template<>
struct DataType< ::robotnik_msgs_new::SetNamedDigitalOutputResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs_new::SetNamedDigitalOutput >::value();
  }
  static const char* value(const ::robotnik_msgs_new::SetNamedDigitalOutputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_NEW_MESSAGE_SETNAMEDDIGITALOUTPUT_H
