// Generated by gencpp from file ur_msgs_new/SetIO.msg
// DO NOT EDIT!


#ifndef UR_MSGS_NEW_MESSAGE_SETIO_H
#define UR_MSGS_NEW_MESSAGE_SETIO_H

#include <ros/service_traits.h>


#include <ur_msgs_new/SetIORequest.h>
#include <ur_msgs_new/SetIOResponse.h>


namespace ur_msgs_new
{

struct SetIO
{

typedef SetIORequest Request;
typedef SetIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetIO
} // namespace ur_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs_new::SetIO > {
  static const char* value()
  {
    return "e1b580ccf43a938f2efbbb98bbe3e277";
  }

  static const char* value(const ::ur_msgs_new::SetIO&) { return value(); }
};

template<>
struct DataType< ::ur_msgs_new::SetIO > {
  static const char* value()
  {
    return "ur_msgs_new/SetIO";
  }

  static const char* value(const ::ur_msgs_new::SetIO&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs_new::SetIORequest> should match
// service_traits::MD5Sum< ::ur_msgs_new::SetIO >
template<>
struct MD5Sum< ::ur_msgs_new::SetIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs_new::SetIO >::value();
  }
  static const char* value(const ::ur_msgs_new::SetIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs_new::SetIORequest> should match
// service_traits::DataType< ::ur_msgs_new::SetIO >
template<>
struct DataType< ::ur_msgs_new::SetIORequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs_new::SetIO >::value();
  }
  static const char* value(const ::ur_msgs_new::SetIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs_new::SetIOResponse> should match
// service_traits::MD5Sum< ::ur_msgs_new::SetIO >
template<>
struct MD5Sum< ::ur_msgs_new::SetIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs_new::SetIO >::value();
  }
  static const char* value(const ::ur_msgs_new::SetIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs_new::SetIOResponse> should match
// service_traits::DataType< ::ur_msgs_new::SetIO >
template<>
struct DataType< ::ur_msgs_new::SetIOResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs_new::SetIO >::value();
  }
  static const char* value(const ::ur_msgs_new::SetIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_NEW_MESSAGE_SETIO_H
