// Generated by gencpp from file ur_msgs_new/SetSpeedSliderFraction.msg
// DO NOT EDIT!


#ifndef UR_MSGS_NEW_MESSAGE_SETSPEEDSLIDERFRACTION_H
#define UR_MSGS_NEW_MESSAGE_SETSPEEDSLIDERFRACTION_H

#include <ros/service_traits.h>


#include <ur_msgs_new/SetSpeedSliderFractionRequest.h>
#include <ur_msgs_new/SetSpeedSliderFractionResponse.h>


namespace ur_msgs_new
{

struct SetSpeedSliderFraction
{

typedef SetSpeedSliderFractionRequest Request;
typedef SetSpeedSliderFractionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeedSliderFraction
} // namespace ur_msgs_new


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs_new::SetSpeedSliderFraction > {
  static const char* value()
  {
    return "172aeb6c49379a44cf68480fa5bfad3c";
  }

  static const char* value(const ::ur_msgs_new::SetSpeedSliderFraction&) { return value(); }
};

template<>
struct DataType< ::ur_msgs_new::SetSpeedSliderFraction > {
  static const char* value()
  {
    return "ur_msgs_new/SetSpeedSliderFraction";
  }

  static const char* value(const ::ur_msgs_new::SetSpeedSliderFraction&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs_new::SetSpeedSliderFractionRequest> should match
// service_traits::MD5Sum< ::ur_msgs_new::SetSpeedSliderFraction >
template<>
struct MD5Sum< ::ur_msgs_new::SetSpeedSliderFractionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs_new::SetSpeedSliderFraction >::value();
  }
  static const char* value(const ::ur_msgs_new::SetSpeedSliderFractionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs_new::SetSpeedSliderFractionRequest> should match
// service_traits::DataType< ::ur_msgs_new::SetSpeedSliderFraction >
template<>
struct DataType< ::ur_msgs_new::SetSpeedSliderFractionRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs_new::SetSpeedSliderFraction >::value();
  }
  static const char* value(const ::ur_msgs_new::SetSpeedSliderFractionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs_new::SetSpeedSliderFractionResponse> should match
// service_traits::MD5Sum< ::ur_msgs_new::SetSpeedSliderFraction >
template<>
struct MD5Sum< ::ur_msgs_new::SetSpeedSliderFractionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs_new::SetSpeedSliderFraction >::value();
  }
  static const char* value(const ::ur_msgs_new::SetSpeedSliderFractionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs_new::SetSpeedSliderFractionResponse> should match
// service_traits::DataType< ::ur_msgs_new::SetSpeedSliderFraction >
template<>
struct DataType< ::ur_msgs_new::SetSpeedSliderFractionResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs_new::SetSpeedSliderFraction >::value();
  }
  static const char* value(const ::ur_msgs_new::SetSpeedSliderFractionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_NEW_MESSAGE_SETSPEEDSLIDERFRACTION_H
