(cl:in-package robotnik_msgs_new-msg)
(cl:export '(STATE-VAL
          STATE
          STATUS-VAL
          STATUS
          COMMUNICATIONSTATUS-VAL
          COMMUNICATIONSTATUS
          STATUSWORD-VAL
          STATUSWORD
          DRIVEFLAGS-VAL
          DRIVEFLAGS
          ACTIVESTATUSWORD-VAL
          ACTIVESTATUSWORD
          ACTIVEDRIVEFLAGS-VAL
          ACTIVEDRIVEFLAGS
          DIGITALOUTPUTS-VAL
          DIGITALOUTPUTS
          DIGITALINPUTS-VAL
          DIGITALINPUTS
          AVERAGECURRENT-VAL
          AVERAGECURRENT
          ANALOGINPUTS-VAL
          ANALOGINPUTS
))